services:
    website:
        build: ./website
        ports:
            - "3000:3000"
        environment:
            API_URL: ${API_URL}
            API_KEY: ${API_KEY}
        depends_on:
            - api
    bot:
        build: ./bot
        depends_on:
            - api

    api:
        build: ./api
        depends_on:
            - db
        ports:
            - "4000:4000"
        environment:
            DB_URL: ${DB_URL}
            API_KEY: ${API_KEY}

    db:
        image: postgres:13.18-alpine3.20
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

volumes:
    db_data:
