import type { BombPartyRules, CustomBonusAlphabet, DictionaryId, DictionaryManifest } from "../types/gameTypes";

export const jklmDomain = "jklm.fun";

function enabledBonusLetters(bonusAlphabet: CustomBonusAlphabet): string {
    return Object.entries(bonusAlphabet)
        .filter(([, count]) => count > 0)
        .map(([letter]) => letter)
        .join("");
}

/** jklm BombParty dictionary ids (matches BBv7 / jklm platform). */
export const dictionaryIds = ["en", "fr", "de", "it", "es", "pt-BR"] as const;

/** BirdBot / BBv7 default customBonusAlphabet per dictionary (1 = enabled, 0 = disabled). */
export const defaultBonusAlphabetsByDictionaryId: Record<DictionaryId, CustomBonusAlphabet> = {
    en: {
        a: 1,
        b: 1,
        c: 1,
        d: 1,
        e: 1,
        f: 1,
        g: 1,
        h: 1,
        i: 1,
        j: 1,
        k: 1,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        p: 1,
        q: 1,
        r: 1,
        s: 1,
        t: 1,
        u: 1,
        v: 1,
        w: 1,
        x: 0,
        y: 1,
        z: 0,
    },
    fr: {
        a: 1,
        b: 1,
        c: 1,
        d: 1,
        e: 1,
        f: 1,
        g: 1,
        h: 1,
        i: 1,
        j: 1,
        k: 0,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        p: 1,
        q: 1,
        r: 1,
        s: 1,
        t: 1,
        u: 1,
        v: 1,
        w: 0,
        x: 0,
        y: 0,
        z: 0,
    },
    es: {
        a: 1,
        b: 1,
        c: 1,
        d: 1,
        e: 1,
        f: 1,
        g: 1,
        h: 1,
        i: 1,
        j: 1,
        k: 0,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        p: 1,
        q: 1,
        r: 1,
        s: 1,
        t: 1,
        u: 1,
        v: 1,
        w: 0,
        x: 0,
        y: 0,
        z: 0,
    },
    de: {
        a: 1,
        b: 1,
        c: 1,
        d: 1,
        e: 1,
        f: 1,
        g: 1,
        h: 1,
        i: 1,
        j: 0,
        k: 1,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        p: 1,
        q: 0,
        r: 1,
        s: 1,
        t: 1,
        u: 1,
        v: 1,
        w: 1,
        x: 0,
        y: 0,
        z: 1,
    },
    it: {
        a: 1,
        b: 1,
        c: 1,
        d: 1,
        e: 1,
        f: 1,
        g: 1,
        h: 1,
        i: 1,
        j: 0,
        k: 0,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        p: 1,
        q: 1,
        r: 1,
        s: 1,
        t: 1,
        u: 1,
        v: 1,
        w: 0,
        x: 0,
        y: 0,
        z: 1,
    },
    "pt-BR": {
        a: 1,
        b: 1,
        c: 1,
        d: 1,
        e: 1,
        f: 1,
        g: 1,
        h: 1,
        i: 1,
        j: 1,
        k: 0,
        l: 1,
        m: 1,
        n: 1,
        o: 1,
        p: 1,
        q: 1,
        r: 1,
        s: 1,
        t: 1,
        u: 1,
        v: 1,
        w: 0,
        x: 0,
        y: 0,
        z: 0,
    },
};

function manifestFor(dictionaryId: DictionaryId, name: string): DictionaryManifest {
    return {
        name,
        bonusLetters: enabledBonusLetters(defaultBonusAlphabetsByDictionaryId[dictionaryId]),
        promptDifficulties: { beginner: 500, medium: 300, hard: 100 },
    };
}

export const dictionaryManifests: Record<DictionaryId, DictionaryManifest> = {
    en: manifestFor("en", "English"),
    fr: manifestFor("fr", "French"),
    es: manifestFor("es", "Spanish"),
    de: manifestFor("de", "German"),
    it: manifestFor("it", "Italian"),
    "pt-BR": manifestFor("pt-BR", "Brazilian Portuguese"),
};

export const defaultBombPartyRules: BombPartyRules = {
    dictionaryId: "en",
    minTurnDuration: 5,
    promptDifficulty: "custom",
    customPromptDifficulty: 1,
    maxPromptAge: 16,
    startingLives: 2,
    maxLives: 3,
    customBonusAlphabet: defaultBonusAlphabetsByDictionaryId.en,
};

export const promptDifficulties = ["beginner", "medium", "hard", "custom"] as const;
export const alphabet = "abcdefghijklmnopqrstuvwxyz" as const;
export const submitResults = ["success", "failsPrompt", "invalidWord", "noText", "alreadyUsed", "bombExploded"] as const;

export const failWordReasons = ["notInDictionary", "alreadyUsed", "wrongPrompt", "tooShort"] as const;
