import { jklmDomain } from "../../../lib/constants/gameConstants";
import { DISCORD_SERVER_LINK, GITHUB_REPO_LINK, PAYPAL_DONATE_LINK, WEBSITE_LINK } from "../BirdBotConstants";
import { ResourceText } from "./englishTexts";

export const portugueseTexts = {
    error: {
        intro: "Erro:",
        missing_text: "O texto traduzido está faltando. Isso não deveria acontecer. Pode reportar isso no servidor do Discord?",
        unspecific: "$t(error.intro) Ocorreu um erro desconhecido.",
        api: {
            inaccessible: "$t(error.intro) A API não está acessível. Tenta de novo mais tarde!",
            conflict: "$t(error.intro) Essa operação entra em conflito com o estado atual da conta.",
        },
        roomState: {
            noGameInProgress: "$t(error.intro) Não há partida em andamento.",
            notInPregame: "$t(error.intro) Não há partida em fase de preparação.",
            notEnoughPlayers: "$t(error.intro) Não há jogadores suficientes para começar a partida.",
            cannotSetMode: "$t(error.intro) Não é possível mudar o modo fora da fase de preparação.",
            cannotSetLanguage: "$t(error.intro) Não é possível mudar o idioma fora da fase de preparação.",
            cannotSetBonusAlphabet:
                "$t(error.intro) Não é possível mudar as letras bônus fora da fase de preparação.",
        },
        invalid: {
            regex: "$t(error.intro) Regex inválida: {{regex}}",
            language: "$t(error.intro) Idioma inválido.",
            gameMode: "$t(error.intro) Modo de jogo inválido.",
        },
        notSupported: {
            language: '$t(error.intro) O idioma "{{language}}" não é suportado.',
            listedRecordNotExistsInLanguage: "$t(error.intro) O record à lista solicitado não existe na língua solicitada.",
        },
        "404": {
            word: "$t(error.intro) A palavra não está no dicionário.",
            player: "$t(error.intro) Jogador não encontrado.",
            gamer: "$t(error.intro) Jogador não encontrado na sala. Isso não deveria acontecer.",
            dictionaryResource:
                "$t(error.intro) Não foi possível encontrar o recurso do dicionário para este idioma. Isso não deveria acontecer.",
            playerStats: "$t(error.intro) Não foram encontradas pontuações para este jogador. Isso não deveria acontecer.",
            currentPlayer: "$t(error.intro) Não há jogador atual.",
            syllableNotExists: "$t(error.intro) Esta sílaba não existe em nenhuma palavra do dicionário solicitado.",
        },
        searchWords: {
            nonsensicalRecordSearch: "$t(error.intro) Não faz sentido ordenar palavras por record(s): {{records}}.",
            multipleRecords: "$t(error.intro) Você só pode ordenar por um record de ordenação por vez.",
            mustProvideOneSyllable:
                "$t(error.intro) Você só pode ordenar por palavras multissilábicas se fornecer exatamente uma sílaba.",
            noArguments: "$t(error.intro) Você precisa fornecer pelo menos uma sílaba ou regex.",
        },
        invalidParams: {
            noUsername: "$t(error.intro) Você precisa fornecer um nome de usuário para usar este comando.",
            mustProvideWord: "$t(error.intro) Você precisa fornecer uma palavra para usar este comando.",
        },
        platform: {
            mustBeLoggedIn: `$t(error.intro) Você precisa estar logado no jklm.fun para usar este comando. Para fazer login, vá para a página inicial https://${jklmDomain}/ e clique em "Entrar" se você tem uma conta ou "Nova conta" se não tem.`,
        },
    },
    command: {
        help: {
            description: "Mostra a lista de comandos. Se você indicar um comando, mostra sua descrição.",
            list: "{{commandList}} — Para mais info sobre um comando, use /help [comando]",
            details: "/{{commandName}}: {{description}} — Uso: {{usage}} — Ex. {{example}}",
        },
        speedRecords: { description: "Mostra os tempos mais rápidos para atingir marcos de cada categoria." },
        accuracyRecords: { description: "Mostra o menor número de palavras usado para atingir marcos de cada categoria." },
        feathers: { description: "Mostra seu saldo de penas do BirdBot." },
        economy: { description: "Mostra penas, status VIP e compras de um jogador." },
        buy: { description: "Compra VIP com penas do BirdBot." },
        setName: { description: "Altera o nome do seu perfil do BirdBot." },
        welcomeMessage: { description: "Define sua mensagem de boas-vindas." },
        roomName: { description: "Define o nome das salas que você cria." },
        botName: { description: "Define o nome do BirdBot nas suas salas." },
        picture: { description: "Copia sua foto de perfil atual do jklm.fun para o BirdBot nas salas que você cria." },
        news: { description: "Mostra as últimas notícias publicadas." },
        trust: { description: "Administra a confiança dos revisores pela API." },
        blacklist: { description: "Administra a lista negra de salas pela API." },
        connect: {
            description: "Explica como entrar no jklm.fun.",
            result: "Para se conectar ao jklm.fun, abra https://jklm.fun, clique no seu apelido no canto superior direito e escolha Twitch ou Discord.",
        },
        admin: {
            creatorId: "Auth id do criador da sala: {{id}}",
            reconnecting: "Reconectando esta sala...",
            getId: "Correspondência: {{account}} / {{username}} ({{playerId}})",
            suppressUsage: "Uso: /suppress [jogador] [motivo?]",
            suppressResult: "Suprimido {{player}}: {{suppressed}}",
            giveFeathersUsage: "Uso: /givefeathers [jogador] [quantidade]",
            giveFeathersResult: "Ajustado {{player}} em {{amount}} penas. Saldo: {{balance}}.",
            giveXpUsage: "Uso: /givexp [jogador] [quantidade]",
            giveXpResult: "Ajustado {{player}} em {{amount}} XP. XP total: {{xp}}.",
            setXpUsage: "Uso: /setxp [jogador] [quantidade]",
            setXpResult: "XP de {{player}} definida para {{xp}}.",
            health: "Saúde — salas {{rooms}} (conectadas {{connected}}), API {{api}}, uptime {{uptime}}",
            staffUsage: "Uso: /staff [add|remove|show] [admin|automod] [jogador]",
            staffShow: "Admins: {{admins}} — Automods: {{automods}}",
            staffUpdated: "Staff atualizado. Admins: {{admins}} — Automods: {{automods}}",
            staffEmpty: "(nenhum)",
        },
        parity: {
            accuracyValue: "{{value}} palavras",
            recordDoesNotExist: "$t(error.intro) A categoria “{{record}}” não existe para este idioma.",
            noRecordsForCategory: "Ainda não há recordes de {{category}}.",
            pageDoesNotExist: "A página de marco {{page}} ainda não existe para {{category}}.",
            categoryRecords: "{{category}}, marco {{milestone}} — {{records}}",
            globalRecords: "Recordes de {{mode}} — {{records}}",
            noRecordsYet: "Ainda não há recordes de {{mode}}.",
            feathers: "Você tem {{count}} penas.",
            economy: "{{player}}: {{feathers}} penas — {{tier}} — {{purchases}} compra(s).",
            purchaseLogin: "Você precisa entrar na conta para fazer uma compra.",
            availableSkus: "Ofertas disponíveis: VIP (500 penas).",
            alreadyVip: "Você já tem VIP.",
            purchasedVip: "VIP comprado.",
            insufficientFeathers: "Você não tem penas suficientes.",
            setNameLogin: "Você precisa entrar na conta para definir um nome de perfil.",
            invalidName: "O nome do perfil deve ter de 2 a 20 caracteres.",
            nameSet: "Seu nome de perfil do BirdBot agora é {{name}}.",
            nameClaimed: "Esse nome de perfil já está em uso.",
            nameCooldown: "Você só pode mudar seu nome a cada 30 dias.",
            cosmeticLogin: "Você precisa entrar na conta para personalizar seu perfil do BirdBot.",
            cosmeticValue: "Informe um valor ou use /{{command}} clear.",
            cosmeticTooLong: "Esse valor deve ter no máximo {{maxLength}} caracteres.",
            cosmeticTier: "Essa personalização requer VIP.",
            cosmeticCleared: "Personalização removida.",
            cosmeticSaved: "Personalização salva.",
            pictureCopied: "A foto de perfil do seu BirdBot foi alterada!",
            pictureUnavailable: "Não foi possível ler sua foto de perfil atual do jklm.fun.",
            noNews: "Não há notícias publicadas do BirdBot.",
            moderationUsage: "Uso: /{{command}} [add|remove|show] [jogador].",
            moderationState: "{{player}}: confiança {{trust}}, lista negra {{blacklist}}.",
            yesWithReason: "sim ({{reason}})",
            yes: "sim",
            no: "não",
            noReason: "sem motivo",
        },
        records: {
            description: "Mostra a lista de records.",
            specificRecord: "[{{languageFlag}} {{gameMode}} {{recordType}}] {{records}}",
            allRecords: "[{{languageFlag}} {{gameMode}}] {{records}}",
        },
        currentGameScore: {
            description:
                "Mostra as pontuações atuais da partida para um jogador. Se você não indicar um jogador, mostra as pontuações do jogador atual.",
            result: "{{username}}: {{scores}}",
            noScores: "{{username}}: Não há pontuações disponíveis",
        },
        startGame: {
            description: "Inicia a partida.",
            starting: "Iniciando partida...",
        },
        setGameMode: {
            description: "Muda o modo de jogo.",
            alreadySet: "O modo de jogo já está em {{gameMode}}.",
            setting: "Mudando modo para {{gameMode}}...",
        },
        setRoomLanguage: {
            description: "Muda o idioma da sala.",
            alreadySet: "O idioma da sala já é {{language}}.",
            setting: "A sala agora está em {{language}}.",
        },
        train: {
            description:
                "Ativa um modo de treino onde você tem que colocar o máximo de palavras da sua lista de treino que conseguir. Uso: /train [RegExps...] ou /train [record]",
        },
        searchWords: {
            description:
                "Procura palavras no dicionário. Você pode dar quantas sílabas ou regex quiser. O comando vai te dar as palavras que correspondem a cada regex.",
            result: "[{{recordTypes}}{{resultCount}} res. ({{hiddenCount}} ocultos)] {{wordsList}}",
            noResults: "[{{recordTypes}}{{resultCount}} res. ({{hiddenCount}} ocultos)] Não há resultados disponíveis",
            previousSyllableHint:
                "Em vez de filtrar palavras para o record {{recordType}}, você pode fornecer várias regex. Exemplo: /c ER FA, se ER é a sílaba atual e FA a sílaba anterior.",
            alphaHint:
                "Em vez de filtrar palavras para o record {{recordType}}, você pode fornecer várias regex. Exemplo: /c ^E FA, se E é a letra alpha atual e FA é a sílaba atual.",
        },
        playerProfile: {
            description: "Mostra o perfil de um jogador.",
            noUsernameNotConnected:
                "Você precisa estar conectado ao jklm.fun para verificar seu próprio perfil. Se você quiser verificar o perfil de outro jogador, use a sintaxe /p [nome de usuário].",
            result: "[{{languageFlag}}] {{playerUsername}}: Classificação #{{rank}} com {{pp}}pp, {{currentLevelXp}}/{{totalLevelXp}}xp, nível {{level}}. Top 5 desempenhos: {{topPerformances}}. {{profileLink}}",
        },
        playerRecords: {
            description: "Mostra os recordes de um jogador para um idioma e modo de jogo.",
            noUsernameNotConnected:
                "Você precisa estar conectado ao jklm.fun para ver seus próprios recordes. Para ver os de outro jogador, use /pr [nome de usuário].",
            result: "[{{languageFlag}} {{gameMode}}] {{playerUsername}}: {{records}}. {{profileLink}}",
            noRecords: "[{{languageFlag}} {{gameMode}}] {{playerUsername}}: Não há records nesta categoria",
        },
        xp: {
            description: "Mostra o XP e o nível de um jogador.",
            noUsernameNotConnected:
                "Você precisa estar conectado ao jklm.fun para ver seu próprio XP. Para ver o XP de outro jogador, use /xp [nome de usuário].",
            result: "{{playerUsername}}: nível {{level}} — {{currentLevelXp}}/{{totalLevelXp}}xp ({{totalXp}} total)",
        },
        showTime: {
            description: "Mostra há quanto tempo a partida atual está rolando.",
            result: "Tempo de partida: {{time}}",
        },
        changeBonusAlphabet: {
            description:
                "Muda o alfabeto bônus. /bl default para os valores padrão, /bl reset para zerar e depois definir, ou /bl a:1 b:0 para alterar letras.",
            setting: "Alterando as letras bônus...",
            invalidFormat:
                "$t(error.intro) Formato inválido. Exemplos: /bl default — /bl a:1 z:0 — /bl reset q:1",
            invalidRange: "$t(error.intro) As contagens de letras devem estar entre 0 e 99.",
        },
        destroyRoom: {
            description: "Destrói a sala atual.",
            destroying: "Destruindo a sala...",
        },
        getBomb: {
            description: "Boom.",
            result: "💥",
        },
        getDefinition: {
            description: "Procura a definição de uma palavra (francês e inglês).",
            result: "{{word}} ({{source}}) [{{page}}/{{total}}]: {{definition}}",
            notFound: "$t(error.intro) Nenhuma definição encontrada.",
            notFoundSuggestion: "$t(error.intro) Nenhuma definição encontrada. Você quis dizer {{suggestion}}?",
            notSupported: "$t(error.intro) Definições não estão disponíveis para {{language}}.",
        },
        rareSyllables: {
            description: "Mostra as sílabas raras no dicionário.",
            result: "[{{languageFlag}}] Sílabas raras em {{word}}: {{rareSyllables}}",
            noneFound: "[{{languageFlag}}] Sílabas raras em {{word}}: Nenhuma",
            errorSyllableNotInDictionary:
                "$t(error.intro) Uma das sílabas da palavra fornecida não está no dicionário. Isso não deveria acontecer. Pode reportar isso no servidor do Discord?",
        },
        broadcast: {
            description: "Envia uma mensagem para todos os jogadores em todas as salas.",
            message: "Difusão: {{message}}",
        },
        discord: {
            description: "Fornece o link do servidor Discord.",
            result: "Servidor Discord: {{link}} - Entre no servidor para ter as últimas novidades e atualizações!",
        },
        github: {
            description: "Fornece o link do repositório do GitHub.",
            result: "Repositório do GitHub: {{link}} - Dê uma estrela se você curte o projeto e quer nos apoiar!",
        },
        donate: {
            description: "Fornece o link de doação PayPal.",
            result: "Link para doação no PayPal: {{link}} - Muito obrigado pelo seu apoio!",
        },
        website: {
            description: "Fornece o link do site.",
            result: "Site: {{link}} - No site você vai encontrar todos os records dos jogadores, a doc dos comandos, e muito mais!",
        },
        uptime: {
            description: "Mostra o tempo de funcionamento do bot.",
            result: "Tempo de funcionamento: {{uptime}}",
        },
        modUser: {
            description: "Dá permissões de moderador para um jogador.",
            modding: "Moderando {{username}}...",
        },
        unmodUser: {
            description: "Remove as permissões de moderador de um jogador.",
            unmodding: "Removendo moderação de {{username}}...",
        },
        privateRoom: {
            description: "Cria uma sala privada.",
            setting: "A sala agora é privada...",
        },
        publicRoom: {
            description: "Cria uma sala pública.",
            setting: "A sala agora é pública...",
        },
        destroyAllRooms: {
            description: "Destrói todas as salas.",
            message: "Destruindo todas as salas, provavelmente para manutenção. BirdBot voltará em breve!",
        },
        showAllRooms: {
            description: "Mostra todas as salas.",
            result: "Salas: {{roomsList}}",
        },
        createRoom: {
            description: "Cria uma sala.",
            roomCreated: `Sala criada: https://${jklmDomain}/{{roomCode}}`,
            roomAlreadyExists: `Você já é o proprietário de uma sala: https://${jklmDomain}/{{roomCode}}`,
            roomBeingCreated: "A sala está sendo criada, por favor, aguarde um pouco...",
            unknownError: "$t(error.intro) Um erro desconhecido ocorreu ao criar a sala. Por favor, tente novamente mais tarde.",
        },
        linkAccount: {
            description:
                "Relaciona sua conta Discord à sua conta jklm.fun. Isso é útil se você quiser usar as funcionalidades do site (e o bot Discord que está chegando em breve).",
            tokenNotFound: "O token é inválido ou expirou.",
            success:
                "Sua conta Discord foi relacionada à sua conta jklm.fun. Agora você pode usar as funcionalidades do site.",
        },
        test: {
            description: "Comando de teste para admins.",
        },
    },
    general: {
        playerStats: {
            diedLevelUp:
                "{{username}} morreu à {{time}} — +{{gainedXp}}xp, {{oldCurrentLevelXp}}/{{oldTotalLevelXp}}xp nível {{oldLevel}} -> {{newCurrentLevelXp}}/{{newTotalLevelXp}}xp nível {{newLevel}} — Scores: {{scores}}",
            died: "{{username}} morreu à {{time}} — +{{gainedXp}}xp — Scores: {{scores}}",
            diedNoWords: "{{username}} morreu sem colocar nenhuma palavra nesta partida. Boa sorte na próxima!",
        },
        roomState: {
            gameModeSet: "Modo de jogo mudado para {{gameMode}}.",
        },
        scorePresentation: "{{username}} com {{score}}",
        greet: `Bem-vindo! Servidor Discord: ${DISCORD_SERVER_LINK}. Para mais informações, use /help ou vá para ${WEBSITE_LINK}`,
    },
    eventHandler: {
        chat: {
            commandNotFound: "Comando não encontrado: {{command}}",
            noCommandGiven: "Você precisa informar um comando depois do prefixo.",
            notRoomCreator:
                "Você não pode usar este comando se não for o criador da sala. /b para criar sua sala estará disponível em breve.",
            notAdmin: "Você não pode usar este comando se não for um administrador.",
            notAccessibleInRound: "Este comando não está disponível durante uma rodada.",
            notAllowedFromWordInput: "Este comando não pode ser usado na entrada de palavras.",
            cooldown: "Espere antes de usar esse comando novamente.",
        },
        moderation: {
            invalidNickname: "⛔ {{username}}: apelido bloqueado ({{reason}}).",
            bannedWord: "palavra proibida",
            bannedCharacter: "caractere proibido",
            blacklisted: "⛔ {{username}}: a conta está na lista negra.",
            spamTimeout: "⛔ {{username}}: expulsão temporária por spam.",
            spamWarning: "⚠️ {{username}}: vá mais devagar.",
        },
        submit: {
            turnCommentWithWord: "{{username}}: {{comments}} ({{word}})",
            turnCommentWithoutWord: "{{username}}: {{comments}}.",
            comments: {
                gainedLives: "ganhou {{count}} vidas ({{playerTotal}}/{{globalTotal}})",
                reachedWordsNoDeath: "alcançou {{count}} palavras sem morrer",
                reachedMetaMilestone: "alcançou o marco {{milestone}} de {{category}} em velocidade e precisão",
                reachedSpeedMilestone: "alcançou o marco {{milestone}} de {{category}} em velocidade",
                reachedAccuracyMilestone: "alcançou o marco {{milestone}} de {{category}} em precisão",
                placedLongWord: "colocou uma palavra longa ({{playerTotal}}/{{globalTotal}})",
                placedHyphenatedWord: "colocou uma palavra composta ({{playerTotal}}/{{globalTotal}})",
                completedAlpha: "completou um alpha: {{alphaString}}",
                placedPreviousSyllable: "colocou uma sílaba anterior: {{syllable}} ({{playerTotal}}/{{globalTotal}})",
                gainedMultiSyllables: "ganhou {{count}} MS ({{prompt}} x {{multiplier}}) ({{playerTotal}}/{{globalTotal}})",
                depletedSyllables: "esgotou {{count}} sílaba(s): {{syllables}} ({{playerTotal}}/{{globalTotal}})",
                listedRecord: "{{commentIntroduction}} ({{playerTotal}}/{{globalTotal}})",
            },
            listedRecordCommentIntroductions: {
                adverb: "colocou um advérbio",
                chemical: "colocou um elemento químico",
                creature: "colocou uma criatura",
                ethnonym: "colocou um gentílico",
                plant: "colocou uma planta",
                slur: "colocou uma palavra ofensiva",
                food: "colocou um alimento",
            },
        },
    },
    periodic: {
        support: {
            star: `Hey! Se você gosta de BirdBot e quer nos apoiar, dê uma estrela no GitHub! Isso significa muito para nós! ${GITHUB_REPO_LINK}`,
            donate: `Hey! Se você gosta de BirdBot e quer nos apoiar, faça um doação no PayPal! Muito obrigado! ${PAYPAL_DONATE_LINK}`,
        },
    },
    parity: {
        gameplay: {
            customMode: "Modo personalizado ativado; a pontuação ranqueada está desativada.",
            providePlaystyle: "Informe um estilo de jogo.",
            unavailablePlaystyle: "Esse estilo de jogo não está disponível no idioma atual.",
            playstyleEnabled: "Estilo de jogo {{playstyle}} ativado.",
            tooManyTrainingMatches: "Erro: os seus parâmetros de /train resultam em mais de {{max}} resultados. Por favor, utilize parâmetros mais seletivos.",
            noTrainingMatches: "Erro: os seus parâmetros de /train não retornaram nenhum resultado.",
            trainingEnabled: "Modo de treino ativo. Agora você pode usar /c em quaisquer circunstâncias.",
            trainingDisabled: "Você não está mais treinando.",
            trainingConfigured: "A sua lista de treino foi aplicada com {{count}} resultados. Método de ordenação: {{sort}}. Lista: {{list}}.",
            trainingSuccess: "[TRAIN ✅] ({{successes}}/{{attempts}}, {{percentage}}%)",
            trainingFail: "[TRAIN ❌] [{{prompt}}] Poderia ter colocado: {{suggestions}} ({{successes}}/{{attempts}}, {{percentage}}%)",
            regexTooExpensive: "Erro: seus RegExps são muito caros.",
            notImplemented: "Essa funcionalidade ainda não foi implementada.",
            unrankedReason: "Os recordes não serão contabilizados. Motivo: {{reason}}.",
            unrankedReasonCustom: "Modo personalizado ativado",
            unrankedReasonTraining: "Modo de treino ativo",
            scoresWillCountAfterGame: "Seus recordes contarão após essa partida.",
            scoresNowCount: "Os recordes voltarão a contabilizar. ✅",
            invalidRegex: "Expressão regular inválida ou muito custosa.",
            unrankedScores: "{{username}}: {{scores}} (sala não ranqueada).",
            noScores: "sem pontuações",
            scoresNotSaved: "{{username}}: pontuações não salvas ({{reason}}).",
            scoresNotSavedGuest: "jogador não conectado",
            scoresNotSavedBlacklisted: "conta na lista negra",
            scoresNotSavedApi: "API inacessível após novas tentativas",
        },
        dictionary: {
            trustedReviewer: "Este comando é restrito a revisores confiáveis do dicionário.",
            trustedListReviewer: "Este comando é restrito a revisores confiáveis de listas.",
            listUsage: "Uso: /cl [idioma] [recorde de lista] [add|remove] [palavras...].",
            testWords: "Palavras de teste: {{words}}",
            unknownAdded: "A palavra desconhecida {{word}} é válida e foi adicionada ao dicionário.",
            unknownTested: "A palavra desconhecida {{word}} é válida e foi adicionada à lista de teste.",
            invalidRemoved: "A palavra {{word}} é inválida e foi removida do dicionário.",
            invalidTested: "A palavra {{word}} é inválida e foi adicionada à lista de teste para remoção do dicionário.",
        },
        room: {
            blacklisted: "Esta conta não pode criar salas privadas do BirdBot.",
            verificationUnavailable: "Não foi possível verificar o acesso a salas privadas. Tente novamente mais tarde.",
        },
    },
    lib: {
        mode: {
            easy: "Fácil",
            blitz: "Blitz",
            regular: "Normal",
            sub500: "Sub500",
            sub50: "Sub50",
            freeplay: "Freeplay",
        },
        language: {
            en: { flag: "🇺🇸", name: "Inglês" },
            fr: { flag: "🇫🇷", name: "Francês" },
            es: { flag: "🇪🇸", name: "Espanhol" },
            de: { flag: "🇩🇪", name: "Alemão" },
            it: { flag: "🇮🇹", name: "Italiano" },
            brpt: { flag: "🇧🇷", name: "Português brasileiro" },
        },
        recordType: {
            word: {
                recordName: "Palavras",
                score_one: "{{count}} palavra",
                score_other: "{{count}} palavras",
                score_specific_one: "{{count}} palavra",
                score_specific_other: "{{count}} palavras",
            },
            flips: {
                recordName: "Vidas",
                score_one: "{{count}} vida",
                score_other: "{{count}} vidas",
                score_specific_one: "{{count}} vida",
                score_specific_other: "{{count}} vidas",
            },
            alpha: {
                recordName: "Alpha",
                score: "{{formattedScore}}",
            },
            time: {
                recordName: "Tempo",
                score: "{{formattedScore}}",
            },
            depleted_syllables: {
                recordName: "Sílabas esgotadas",
                score_one: "{{count}} sílaba",
                score_other: "{{count}} sílabas",
                score_specific_one: "{{count}} sílaba esgotada",
                score_specific_other: "{{count}} sílabas esgotadas",
            },
            multi_syllable: {
                recordName: "Multi-sílabas",
                score_one: "{{count}} MS",
                score_other: "{{count}} MS",
                score_specific_one: "{{count}} MS",
                score_specific_other: "{{count}} MS",
            },
            previous_syllable: {
                recordName: "Sílabas anteriores",
                score_one: "{{count}} sílaba",
                score_other: "{{count}} sílabas",
                score_specific_one: "{{count}} sílaba anterior",
                score_specific_other: "{{count}} sílabas anteriores",
            },
            no_death: {
                recordName: "Sem morte",
                score_one: "{{count}} palavra",
                score_other: "{{count}} palavras",
                score_specific_one: "{{count}} palavra sem morrer",
                score_specific_other: "{{count}} palavras sem morrer",
            },
            hyphen: {
                recordName: "Palavras compostas",
                score_one: "{{count}} palavra",
                score_other: "{{count}} palavras",
                score_specific_one: "{{count}} palavra composta",
                score_specific_other: "{{count}} palavras compostas",
            },
            more_than_20_letters: {
                recordName: "Palavras longas",
                score_one: "{{count}} palavra",
                score_other: "{{count}} palavras",
                score_specific_one: "{{count}} palavra longa",
                score_specific_other: "{{count}} palavras longas",
            },
            adverb: {
                recordName: "Advérbios",
                score_one: "{{count}} advérbio",
                score_other: "{{count}} advérbios",
                score_specific_one: "{{count}} advérbio",
                score_specific_other: "{{count}} advérbios",
            },
            chemical: {
                recordName: "Elementos químicos",
                score_one: "{{count}} elemento químico",
                score_other: "{{count}} elementos químicos",
                score_specific_one: "{{count}} elemento químico",
                score_specific_other: "{{count}} elementos químicos",
            },
            creature: {
                recordName: "Criaturas",
                score_one: "{{count}} criatura",
                score_other: "{{count}} criaturas",
                score_specific_one: "{{count}} criatura",
                score_specific_other: "{{count}} criaturas",
            },
            ethnonym: {
                recordName: "Gentílicos",
                score_one: "{{count}} gentílico",
                score_other: "{{count}} gentílicos",
                score_specific_one: "{{count}} gentílico",
                score_specific_other: "{{count}} gentílicos",
            },
            plant: {
                recordName: "Plantas",
                score_one: "{{count}} planta",
                score_other: "{{count}} plantas",
                score_specific_one: "{{count}} planta",
                score_specific_other: "{{count}} plantas",
            },
            food: {
                recordName: "Alimentos",
                score_one: "{{count}} alimento",
                score_other: "{{count}} alimentos",
                score_specific_one: "{{count}} alimento",
                score_specific_other: "{{count}} alimentos",
            },
            slur: {
                recordName: "Ofensas",
                score_one: "{{count}} ofensa",
                score_other: "{{count}} ofensas",
                score_specific_one: "{{count}} ofensa",
                score_specific_other: "{{count}} ofensas",
            },
        },
    },
} satisfies ResourceText;
